better install script
git-svn-id: http://svn.delph-in.net/lkb/trunk@5167 3df82f5b-d43a-0410-af33-fce91db48ec5

diff --git a/etc/install b/etc/install
--- a/etc/install
+++ b/etc/install
@@ -60,8 +60,8 @@ while [ $# -gt 0 ]; do
       shift;
     ;;
     *)
-      echo "install: ignoring invalid parameter \`${1}'.";
-      shift;
+      echo "install: invalid parameter \`${1}'.";
+      exit 1;
     ;;
   esac
 done
